spring:
  application:
    name: nutrilogic
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:postgresql://localhost:5432/nutrilogic
    username: nutrilogic_user
    password: your_password_here
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liLfJfdXxzlmoWNL
            client-secret: d02f205a520f5240a6599b077c0f0f12c2134a93
            scope: read:user, user:email
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: 8080
  error:
    path: /error
    whitelabel:
      enabled: false
